### ISSUE TITLE
cmake : CMake Error: The source directory "D:/opencv_files/opencv" does not appear to contain CMakeLists.txt

### ISSUE THREAD

**Issue by blackbusters** [shimat/opencv_files#6]
Hi..

I'm trying to compile from windows with powershell script ./build_windows.ps1, but i got this error :

cmake : CMake Error: The source directory "D:/opencv_files/opencv" does not appear to contain CMakeLists.txt.
At D:\opencv_files\build_windows.ps1:18 char:5
+     cmake -G "Visual Studio 16 2019" `
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (CMake Error: Th...CMakeLists.txt.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Specify --help for usage, or press the help button on the CMake GUI.

When I clone this repo i got empty folder in opencv and opencv_contrib, is that normal? because I also can't open the folder on your github : https://github.com/shimat/opencv/tree/d40fe356e3ea77fd6b68c6e1ccac6d0a391775ba

**Comment by blackbusters** [comment]
Sorry my mistake, i just need to clone for opencv and opencv_contrib github repo directly.

**Comment by shimat** [comment]
I've created a guide to git clone
https://github.com/shimat/opencv_files#build-for-windows
